# Generated by Django 4.1.7 on 2023-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='created_at',
            new_name='createdat',
        ),
    ]
